CREATE TABLE "PERSON" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FIRSTNAME" VARCHAR(30) NOT NULL,
    "LASTNAME" VARCHAR(60) NOT NULL,
    "NICKNAME" VARCHAR(20)
);

CREATE TABLE "CONTACT" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PERSONID" BIGINT REFERENCES PERSON (ID),
    "TYPE" VARCHAR(10),
    "CONTENT" VARCHAR(50),
    "TITLE" VARCHAR(30)
);