DROP TABLE "CONTACT";
DROP TABLE "PERSON";

CREATE TABLE "PERSON" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FIRSTNAME" VARCHAR(30) NOT NULL,
    "LASTNAME" VARCHAR(60) NOT NULL,
    "NICKNAME" VARCHAR(20)
);

CREATE TABLE "CONTACT" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PERSONID" BIGINT REFERENCES PERSON (ID),
    "TYPE" VARCHAR(10),
    "CONTENT" VARCHAR(50),
    "TITLE" VARCHAR(30)
);



INSERT INTO "PERSON" ("FIRSTNAME", "LASTNAME", "NICKNAME") VALUES('First', 'Blood', 'Yoda');
INSERT INTO "PERSON" ("FIRSTNAME", "LASTNAME", "NICKNAME") VALUES('Bobby', 'Sixkiller', 'Bobo');
INSERT INTO "PERSON" ("FIRSTNAME", "LASTNAME", "NICKNAME") VALUES('Reno', 'Raines', 'Harley');
INSERT INTO "PERSON" ("FIRSTNAME", "LASTNAME", "NICKNAME") VALUES('Cheyenne', 'Phillips', 'Che');
INSERT INTO "PERSON" ("FIRSTNAME", "LASTNAME", "NICKNAME") VALUES('Topper', 'Harley', 'The Top');
INSERT INTO "PERSON" ("FIRSTNAME", "LASTNAME", "NICKNAME") VALUES('Chuck', 'Norris', 'Norek');



    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(1, 'EMAIL', 'yoda@home.com', 'Home email');
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(1, 'EMAIL', 'yoda@company.com', 'Company email'); 
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(1, 'PHONE', '732158969', 'Phone number'); 

    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(2, 'EMAIL', 'bobby@renegade.com', 'Company email'); 
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(2, 'PHONE', '753159742', 'Phone number'); 

    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(3, 'EMAIL', 'reno@renegade.com', 'Company email'); 
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(3, 'PHONE', '963158743', 'Phone number'); 

    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(4, 'EMAIL', 'che@renegade.com', 'Company email'); 
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(4, 'EMAIL', 'chegirl@blonde.com', 'Home email');
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(4, 'PHONE', '856246978', 'Phone number'); 

    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(6, 'EMAIL', 'chuck@god.com', 'Company email'); 
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(6, 'PHONE', '456123789', 'Phone number'); 
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(6, 'EMAIL', 'bigfoot@norris.com', 'Home email'); 
    INSERT INTO "CONTACT" ("PERSONID", "TYPE", "CONTENT", "TITLE") VALUES(6, 'PHONE', '782158979', 'Company phone'); 


